alert = {
    "Regua_HomePincas": "Alerta: falha nos sensores de regua aberta, os sensores deveriam estar ligados.",
    "Regua_HomeBocais": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Regu_Posi": "Alerta: colisão da posicionador e régua.",
    "Regu_Bocal": "Alerta: Suba os bocais ou abra as pinças da régua",
    "Regu_Pren": "Alerta: Abra a prensa ou abra pinças da régua.",
    "Regu_Esti": "Alerta: colisão entre Régua e estiramento.",
    "Regu_PincaAber": "Alerta: sensor da régua ligado com a pinça fechada.",
    "Regu_PincaFech": "Alerta: sensor da régua desligado com a pinça aberta.",
    "Prensa_HomeBocai": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Prensa_HomeBocais": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Prensa_Fechar": "Alerta: aguarde o movimento da régua ou abra as pinças da régua.",
    "Prensa_Abrir": "Alerta: pleno acionado, desligue para abrir a prensa.",
    "Prensa_CargPleno": "Alerta: a prensa deve estar fechada para ligar o pleno.",
    "Prensa_DescPleno": "Alerta: a prensa deve estar fechada para ligar o pleno.",
    "Estira_SensorTop": "Alerta: falha na leitura do sensor do estiramento em cima.",
    "Estira_SensorTopo": "Alerta: falha na leitura do sensor do estiramento em cima.",
    "Estira_Descida": "Alerta: aguarde o movimento da régua ou abra as pinças da régua.",
    "Estira_BocalSubi": "Alerta: falha nos sensores dos bocais, o sensor deveria estar desligado.",
    "Estira_BocalDesc": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Estira_BocalRegu": "Alerta: Abra as pinças da régua para descer os bocais.",
    "Forno_PinFornBai": "Alerta: sensor de pino do forno embaixo acionado.",
    "Forno_PinFornBaixo": "Alerta: sensor de pino do forno embaixo acionado.",
    "Forno_PFTorna": "Alerta: sensor de pré-forma torta acionado.",
    "Forno_SegCamb": "Alerta: segurança de colisão do cambotador com o forno.",
    "Forno_ManSensorC": "Alerta: came acionado com pouca pré-forma na rampa.",
    "Forno_ManSensorCame": "Alerta: came acionado com pouca pré-forma na rampa.",
    "Forno_Aquecendo": "Alerta: forno Aquecendo.",
    "Mesa_Forn": "Alerta: segurança de colisão do cambotador com o forno.",
    "Mesa_Posi": "Alerta: segurança de colisão do cambotador com o forno.",
    "Camb_FornoMesa": "Alerta: a mesa deve estar posicionada para o forno.",
    "Camb_FornoMove": "Alerta: o forno deve estar parado.",
    "Camb_PosiMesa": "Alerta: a mesa deve estar posicionada para o posicionador.",
    "Camb_PosiMesaRec": "Alerta: o posicionador deve estar com a mesa recuada.",
    "Camb_PosiMove": "Alerta: o posicionador deve estar parado e fechado.",
    "Posic_HomeMesaRe": "Alerta: falha nos sensores de mesa recuada.",
    "Posi_CambColis": "Alerta: possível colisão com o cambotador embaixo, verifique as posições.",
    "Posi_ReguColis": "Alerta: possível colisão com a régua (recue a mesa ou abra a pinça).",
    "Posic_MesaAvanc": "Alerta: falha nos sensores de mesa avançada.",
    "Posic_MesaRec": "Alerta: falha nos sensores de mesa recuada.",
    "Alim_FalhaSPFRam": "Alerta: falta de pré-forma na rampa.",
    "Alim_FalhaSPFRampa": "Alerta: falta de pré-forma na rampa.",
    "Alim_FaltaPFRamp": "Alerta: nível baixo de pré-forma na rampa.",
    "Alim_FaltaPFRampa": "Alerta: nível baixo de pré-forma na rampa.",
    "Alim_Descarregan": "Alerta: aguarde até o forno ser descarregado.",
    "Alim_Descarregando": "Alerta: aguarde até o forno ser descarregado.",
    "PFnoForno": "Alerta: aguarde até o forno ser descarregado.",
    "PresComando_Alta": "Alerta: pressão de comando acima de 7bar.",
    "PresComando_Baix": "Alerta: a pressão de comando ficou abaixo de 5bar.",
    "PresComando_Baixa": "Alerta: a pressão de comando ficou abaixo de 5bar.",
    "PresSopro_Alta": "Alerta: pressão de sopro acima do limite definido.",
    "PresSopro_Baixa": "Alerta: pressão de sopro abaixo do limite definido.",
    "LinhaCheia": "Alerta: sensor de linha cheia acionado.",
    "FluxoH2O": "Alerta: Fluxo de água não detectado, verifique alimentação de água.",
    "PortasAbertas": "Alerta: Portas abertas.",
    "TorqueRegua": "Alerta: sobretorque da régua detectado na saída de garrafas.",
    "OleoNivel": "Alerta: Nível de óleo baixo.",
    "OleoPressao": "Alerta: Pressão da bomba de óleo alta.",
    "TempMolde": "Alerta: temperatura da água está acima do setpoint.",
    "StatusFreio": "Alerta: a mesa deve estar posicionada para o posicionador.",
    "Posi_CambColis": "Alerta: possível colisão com o cambotador embaixo, verifique as posições.",
    "AlimentacaoDePFn": "Alerta: Pré forma travada verifique o alimentador",
    "AlimentacaoDePFnoPino": "Alerta: Pré forma travada verifique o alimentador",
    "SegurancaRampa": "Alerta: Falha de segurança na rampa, botão de emergência ou carenagem aberta.",
    "TorquePrensa2": "Alerta: Torque da prensa acima do limite definido.",
    "F0_Forno": "Falha: erro no drive do forno.",
    "F1_Mesa": "Falha: erro no drive da Mesa.",
    "F2_Camb": "Falha: erro no drive do cambotador.",
    "F3_Posic": "Falha: erro no drive do posicionador.",
    "F4_Regua": "Falha: erro no drive da régua.",
    "F5_Prensa": "Falha: erro no drive da prensa.",
    "F6_Estira": "Falha: erro no drive do estiramento.",
    "F7_ControlStop": "Falha: Execução de Parada Controlada.",
    "F8_CS_Forno": "Falha: parada Controlada do Forno (Verifique o Sinal X7 - Pino 4)",
    "F9_CS_Mesa": "Falha: parada Controlada da Mesa(Verifique o Sinal X7 - Pino 4)",
    "F10_CS_Camb": "Falha: parada Controlada do Cambotador (Verifique o Sinal X7 - Pino 4)",
    "F11_CS_Posic": "Falha: parada Controlada do Posicionador (Verifique o Sinal X7 - Pino 4)",
    "F12_CS_Regua": "Falha: parada Controlada da Régua (Verifique o Sinal X7 - Pino 4)",
    "F13_CS_Prensa": "Falha: parada Controlada da prensa (Verifique o Sinal X7 - Pino 4)",
    "F14_CS_Estira": "Falha: parada Controlada do Estiramento (Verifique o Sinal X7 - Pino 4)",
    "F15_OPStop": "Falha: erro detectado em algum drive, verifique as demais falhas.",
    "F16_Emerg": "Alerta: emergência da rampa detectada",
    "F17_ReleFase": "Falha: parada por relé de fase, verifique a tensão do equipamento.",
    "F18_PortaAberta": "Falha: parada por portas abertas.",
    "F19_PincaRegua1Fechada": "Falha: o sensor de régua 1 deve estar desligado quando o cilindro está avançado.",
    "F20_PincaRegua1Aberta": "Falha: o sensor de régua 1 deve estar ligado quando o cilindro está recuado.",
    "F21_PincaRegua2Fechada": "Falha: o sensor de régua 2 deve estar desligado quando o cilindro está avançado.",
    "F22_PincaRegua2Aberta": "Falha: o sensor de régua 2 deve estar ligado quando o cilindro está recuado.",
    "F23_Bocal1UP": "Falha: o sensor do bocal 1 deve estar desligado quando o cilindro está recuado.",
    "F24_Bocal1DW": "Falha: o sensor do bocal 1 deve estar ligado quando o cilindro está avançado.",
    "F25_Bocal2UP": "Falha: o sensor do bocal 2 deve estar desligado quando o cilindro está recuado.",
    "F26_Bocal2DW": "Falha: o sensor do bocal 2 deve estar ligado quando o cilindro está avançado.",
    "F27_Bocal3UP": "Falha: o sensor do bocal 3 deve estar desligado quando o cilindro está recuado.",
    "F28_Bocal3DW": "Falha: o sensor do bocal 3 deve estar ligado quando o cilindro está avançado.",
    "F29_Bocal4UP": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F30_Bocal4DW": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F31_AvancMesaPosic": "Falha: os sensores da mesa do posicionador avançado devem estar ligados quando o cilindro está avançado.",
    "F32_RecuaMesaPosic": "Falha: falha nos sensores de mesa recuada.",
    "F33_SensorEstira": "Falha: o sensor do estiramento deve estar ligado quando o mesmo estiver em cima.",
    "F34_PFTorta": "Falha: sensor de passagem de pré-forma acionado.",
    "F35_PressaoCmdBaixa": "Falha: a pressão de comando ficou abaixo de 5bar.",
    "F36_PressaoCmdAlta": "Falha: a pressão de comando ficou acima de 7bar.",
    "F37_PinFornoAbaixado;": "Falha: sensor do pino do forno embaixo acionado. Verifique o sensor próximo a alimentação de preformas.",
    "F38_CambotadorColisao;": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "F39_PosicReguaColisao": "Falha: colisão da posicionador e régua.",
    "F40_TorqueForno": "Falha: sobretorque no forno.",
    "F41_ReguaPrensa": "Falha: colisão da posicionador e régua.",
    "F42_EixosON": "Falha: Os eixos não habilitaram corretamente.",
    "F43_FreioEsti": "Falha: Freio do estiramento acionado",
    "F44_QuedaPF_no_preForno": "Falha: rotina de queda de preforma no pré-forno ativada, verifique o forno.",
    "QuedaPFnoPreforno": "Falha: rotina de queda de preforma no pré-forno ativada, verifique o forno.",
    "F45_CambForn": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "F46_CambRegu": "Falha: colisão da posicionador e régua.",
    "LinhaDescarrega": "Alerta: Descarregamento ativo pelo sensor de linha cheia.",
}

fault = {
    "F_Forno ": "Falha: erro no drive do forno.",
    "F_Mesa": "Falha: erro no drive da Mesa.",
    "F_Camb": "Falha: erro no drive do cambotador.",
    "F_PosicUp": "Falha: erro no drive do posicionador Superior.",
    "F_PosicDw": "Falha: erro no drive do posicionador Inferior.",
    "F_Regua": "Falha: erro no drive da régua.",
    "F_Prensa": "Falha: erro no drive da prensa.",
    "Prensa": "Falha: erro no drive da prensa.",
    "F_Estira": "Falha: erro no drive do estiramento.",
    "StatusWord__Estira": "Falha: erro no drive do estiramento.",
    "StatusWord__Prensa": "Falha: erro no drive da prensa.",
    "StatusWord__Regua": "Falha: erro no drive da régua.",
    "StatusWord__Posic": "Falha: erro no drive do posicionador.",
    "StatusWord__Camb": "Falha: erro no drive do cambotador.",
    "StatusWord__Mesa": "Falha: erro no drive da Mesa.",
    "StatusWord__Forno": "Falha: erro no drive do forno.",
    "F_ControlStop": "Falha: Execução de Parada Controlada.",
    "F_CS_Forno": "Falha: parada Controlada do Forno (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Mesa": "Falha: parada Controlada da Mesa(Verifique o Sinal X7 - Pino 4)",
    "F_CS_Camb": "Falha: parada Controlada do Cambotador (Verifique o Sinal X7 - Pino 4)",
    "F_CS_PosicUp": "Falha: parada Controlada do Posicionador superior (Verifique o Sinal X7 - Pino 4)",
    "F_CS_PosicDw": "Falha: parada Controlada do Posicionador Inferior (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Regua": "Falha: parada Controlada da Régua (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Prensa": "Falha: parada Controlada da prensa (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Estira": "Falha: parada Controlada do Estiramento (Verifique o Sinal X7 - Pino 4)",
    "F_OPStop": "Falha: erro detectado em algum drive, verifique as demais falhas.",
    "F_Emerg": "Alerta: emergência da rampa detectada",
    "F_ReleFase": "Falha: parada por relé de fase, verifique a tensão do equipamento.",
    "F_PortaAberta": "Falha: parada por portas abertas.",
    "F_PincaRegua1Fechada": "Falha: o sensor de régua 1 deve estar desligado quando o cilindro está avançado.",
    "F_PincaRegua1Aberta": "Falha: o sensor de régua 1 deve estar ligado quando o cilindro está recuado.",
    "F_PincaRegua2Fechada": "Falha: o sensor de régua 2 deve estar desligado quando o cilindro está avançado.",
    "F_PincaRegua2Aberta": "Falha: o sensor de régua 2 deve estar ligado quando o cilindro está recuado.",
    "F_Bocal1UP": "Falha: o sensor do bocal 1 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal1DW": "Falha: o sensor do bocal 1 deve estar ligado quando o cilindro está avançado.",
    "F_Bocal2UP": "Falha: o sensor do bocal 2 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal2DW": "Falha: o sensor do bocal 2 deve estar ligado quando o cilindro está avançado.",
    "F_Bocal3UP": "Falha: o sensor do bocal 3 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal3DW": "Falha: o sensor do bocal 3 deve estar ligado quando o cilindro está avançado.",
    "F_Bocal4UP": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal4DW": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F_AvancMesaPosic": "Falha: os sensores da mesa do posicionador avançado devem estar ligados quando o cilindro está avançado.",
    "F_RecuaMesaPosic": "Falha: falha nos sensores de mesa recuada.",
    "F_SensorEstira": "Falha: o sensor do estiramento deve estar ligado quando o mesmo estiver em cima.",
    "F_PFTorta": "Falha: sensor de passagem de pré-forma acionado.",
    "F_PressaoCmdBaixa": "Falha: a pressão de comando ficou abaixo de 5bar.",
    "F_PressaoCmdAlta": "Falha: a pressão de comando ficou acima de 7bar.",
    "F_PinFornoAbaixado": "Falha: sensor do pino do forno embaixo acionado. Verifique o sensor próximo a alimentação de preformas.",
    "PinFornoAbaixado": "Falha: sensor do pino do forno embaixo acionado. Verifique o sensor próximo a alimentação de preformas.",
    "F_CambotadorColisao": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "F_PosicReguaColisao": "Falha: colisão da posicionador e régua.",
    "F_TorqueForno": "Falha: sobretorque no forno.",
    "F_PosicReguaColisao": "Falha: colisão da posicionador e régua.",
    "F_QuedaPF_no_preForno": "Falha: rotina de queda de preforma no pré-forno ativada, verifique o forno.",
    "F_Camb_no_Forno": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "boZeraFalha": "Reset de falhas.",
    "StatusWord__PosicUp": "Falha: erro no drive do posicionador Superior.",
    "StatusWord__PosicDw": "Falha: erro no drive do posicionador Inferior.",
}
