alert = {
    "Regua_HomePincas": "Alerta: falha nos sensores de regua aberta, os sensores deveriam estar ligados.",
    "Regua_HomeBocais": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Regu_Posi": "Alerta: colisão da posicionador e régua.",
    "Regu_Bocal": "Alerta: Suba os bocais ou abra as pinças da régua",
    "Regu_Pren": "Alerta: Abra a prensa ou abra pinças da régua.",
    "Regu_Esti": "Alerta: colisão entre Régua e estiramento.",
    "Regu_PincaAber": "Alerta: sensor da régua ligado com a pinça fechada.",
    "Regu_PincaFech": "Alerta: sensor da régua desligado com a pinça aberta.",
    "Prensa_HomeBocai": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Prensa_HomeBocais": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Prensa_Fechar": "Alerta: aguarde o movimento da régua ou abra as pinças da régua.",
    "Prensa_Abrir": "Alerta: pleno acionado, desligue para abrir a prensa.",
    "Prensa_CargPleno": "Alerta: a prensa deve estar fechada para ligar o pleno.",
    "Prensa_DescPleno": "Alerta: a prensa deve estar fechada para ligar o pleno.",
    "Estira_SensorTop": "Alerta: falha na leitura do sensor do estiramento em cima.",
    "Estira_Descida": "Alerta: aguarde o movimento da régua ou abra as pinças da régua.",
    "Estira_BocalSubi": "Alerta: falha nos sensores dos bocais, o sensor deveria estar desligado.",
    "Estira_BocalDesc": "Alerta: falha nos sensores dos bocais embaixo, os sensores deveriam estar ligados.",
    "Estira_BocalRegu": "Alerta: Abra as pinças da régua para descer os bocais.",
    "Forno_PinFornBai": "Alerta: sensor de pino do forno embaixo acionado.",
    "Forno_PinFornBaixo": "Alerta: sensor de pino do forno embaixo acionado.",
    "Forno_PFTorna": "Alerta: sensor de pré-forma torta acionado.",
    "Forno_SegCamb": "Alerta: segurança de colisão do cambotador com o forno.",
    "Forno_ManSensorC": "Alerta: came acionado com pouca pré-forma na rampa.",
    "Forno_Aquecendo": "Alerta: forno Aquecendo.",
    "Mesa_Forn": "Alerta: segurança de colisão do cambotador com o forno.",
    "Mesa_Posi": "Alerta: segurança de colisão do cambotador com o forno.",
    "Camb_FornoMesa": "Alerta: a mesa deve estar posicionada para o forno.",
    "Camb_FornoMove": "Alerta: o forno deve estar parado.",
    "Camb_PosiMesa": "Alerta: a mesa deve estar posicionada para o posicionador.",
    "Camb_PosiMesaRec": "Alerta: o posicionador deve estar com a mesa recuada.",
    "Camb_PosiMove": "Alerta: o posicionador deve estar parado e fechado.",
    "Posic_HomeMesaRe": "Alerta: falha nos sensores de mesa recuada.",
    "Posi_CambColis": "Alerta: possível colisão com o cambotador embaixo, verifique as posições.",
    "Posi_ReguColis": "Alerta: possível colisão com a régua (recue a mesa ou abra a pinça).",
    "Posic_MesaAvanc": "Alerta: falha nos sensores de mesa avançada.",
    "Posic_MesaRec": "Alerta: falha nos sensores de mesa recuada.",
    "Alim_FalhaSPFRam": "Alerta: falta de pré-forma na rampa.",
    "Alim_FalhaSPFRampa": "Alerta: falta de pré-forma na rampa.",
    "Alim_FaltaPFRamp": "Alerta: nível baixo de pré-forma na rampa.",
    "Alim_FaltaPFRampa": "Alerta: nível baixo de pré-forma na rampa.",
    "Alim_Descarregan": "Alerta: aguarde até o forno ser descarregado.",
    "Alim_Descarregando": "Alerta: aguarde até o forno ser descarregado.",
    "PFnoForno": "Alerta: aguarde até o forno ser descarregado.",
    "PresComando_Alta": "Alerta: pressão de comando acima de 7bar.",
    "PresComando_Baix": "Alerta: a pressão de comando ficou abaixo de 5bar.",
    "PresComando_Baixa": "Alerta: a pressão de comando ficou abaixo de 5bar.",
    "PresSopro_Alta": "Alerta: pressão de sopro acima do limite definido.",
    "PresSopro_Baixa": "Alerta: pressão de sopro abaixo do limite definido.",
    "LinhaCheia": "Alerta: sensor de linha cheia acionado.",
    "FluxoH2O": "Alerta: Fluxo de água não detectado, verifique alimentação de água.",
    "PortasAbertas": "Alerta: Portas abertas.",
    "TorqueRegua": "Alerta: sobretorque da régua detectado na saída de garrafas.",
    "OleoNivel": "Alerta: Nível de óleo baixo.",
    "OleoPressao": "Alerta: Pressão da bomba de óleo alta.",
    "TempMolde": "Alerta: temperatura da água está acima do setpoint.",
    "StatusFreio": "Alerta: a mesa deve estar posicionada para o posicionador.",
    "Posi_CambColis": "Alerta: possível colisão com o cambotador embaixo, verifique as posições.",
    "AlimentacaoDePFn": "Alerta: Pré forma travada verifique o alimentador",
    "AlimentacaoDePFnoPino": "Alerta: Pré forma travada verifique o alimentador",
    "SegurancaRampa": "Alerta: Falha de segurança na rampa, botão de emergência ou carenagem aberta.",
    "TorquePrensa2": "Alerta: Torque da prensa acima do limite definido.",
    "F0_Forno": "Falha: erro no drive do forno.",
    "F1_Mesa": "Falha: erro no drive da Mesa.",
    "F2_Camb": "Falha: erro no drive do cambotador.",
    "F3_Posic": "Falha: erro no drive do posicionador.",
    "F4_Regua": "Falha: erro no drive da régua.",
    "F5_Prensa": "Falha: erro no drive da prensa.",
    "F6_Estira": "Falha: erro no drive do estiramento.",
    "F7_ControlStop": "Falha: Execução de Parada Controlada.",
    "F8_CS_Forno": "Falha: parada Controlada do Forno (Verifique o Sinal X7 - Pino 4)",
    "F9_CS_Mesa": "Falha: parada Controlada da Mesa(Verifique o Sinal X7 - Pino 4)",
    "F10_CS_Camb": "Falha: parada Controlada do Cambotador (Verifique o Sinal X7 - Pino 4)",
    "F11_CS_Posic": "Falha: parada Controlada do Posicionador (Verifique o Sinal X7 - Pino 4)",
    "F12_CS_Regua": "Falha: parada Controlada da Régua (Verifique o Sinal X7 - Pino 4)",
    "F13_CS_Prensa": "Falha: parada Controlada da prensa (Verifique o Sinal X7 - Pino 4)",
    "F14_CS_Estira": "Falha: parada Controlada do Estiramento (Verifique o Sinal X7 - Pino 4)",
    "F15_OPStop": "Falha: erro detectado em algum drive, verifique as demais falhas.",
    "F16_Emerg": "Alerta: emergência da rampa detectada",
    "F17_ReleFase": "Falha: parada por relé de fase, verifique a tensão do equipamento.",
    "F18_PortaAberta": "Falha: parada por portas abertas.",
    "F19_PincaRegua1Fechada": "Falha: o sensor de régua 1 deve estar desligado quando o cilindro está avançado.",
    "F20_PincaRegua1Aberta": "Falha: o sensor de régua 1 deve estar ligado quando o cilindro está recuado.",
    "F21_PincaRegua2Fechada": "Falha: o sensor de régua 2 deve estar desligado quando o cilindro está avançado.",
    "F22_PincaRegua2Aberta": "Falha: o sensor de régua 2 deve estar ligado quando o cilindro está recuado.",
    "F23_Bocal1UP": "Falha: o sensor do bocal 1 deve estar desligado quando o cilindro está recuado.",
    "F24_Bocal1DW": "Falha: o sensor do bocal 1 deve estar ligado quando o cilindro está avançado.",
    "F25_Bocal2UP": "Falha: o sensor do bocal 2 deve estar desligado quando o cilindro está recuado.",
    "F26_Bocal2DW": "Falha: o sensor do bocal 2 deve estar ligado quando o cilindro está avançado.",
    "F27_Bocal3UP": "Falha: o sensor do bocal 3 deve estar desligado quando o cilindro está recuado.",
    "F28_Bocal3DW": "Falha: o sensor do bocal 3 deve estar ligado quando o cilindro está avançado.",
    "F29_Bocal4UP": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F30_Bocal4DW": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F31_AvancMesaPosic": "Falha: os sensores da mesa do posicionador avançado devem estar ligados quando o cilindro está avançado.",
    "F32_RecuaMesaPosic": "Falha: falha nos sensores de mesa recuada.",
    "F33_SensorEstira": "Falha: o sensor do estiramento deve estar ligado quando o mesmo estiver em cima.",
    "F34_PFTorta": "Falha: sensor de passagem de pré-forma acionado.",
    "F35_PressaoCmdBaixa": "Falha: a pressão de comando ficou abaixo de 5bar.",
    "F36_PressaoCmdAlta": "Falha: a pressão de comando ficou acima de 7bar.",
    "F37_PinFornoAbaixado;": "Falha: sensor do pino do forno embaixo acionado. Verifique o sensor próximo a alimentação de preformas.",
    "F38_CambotadorColisao;": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "F39_PosicReguaColisao": "Falha: colisão da posicionador e régua.",
    "F40_TorqueForno": "Falha: sobretorque no forno.",
    "F41_ReguaPrensa": "Falha: colisão da posicionador e régua.",
    "F42_EixosON": "Falha: Os eixos não habilitaram corretamente.",
    "F43_FreioEsti": "Falha: Freio do estiramento acionado",
    "F44_QuedaPF_no_preForno": "Falha: rotina de queda de preforma no pré-forno ativada, verifique o forno.",
    "QuedaPFnoPreforno": "Falha: rotina de queda de preforma no pré-forno ativada, verifique o forno.",
    "F45_CambForn": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "F46_CambRegu": "Falha: colisão da posicionador e régua.",
    "LinhaDescarrega": "Alerta: Descarregamento ativo pelo sensor de linha cheia.",
    "Portas": "Alerta: portas abertas.",
    "Porta5": "Alerta: porta direita de acesso lateral ao forno aberta.",
    "Porta2": "Alerta: porta 2 aberta.",
    "Porta3": "Alerta: porta 3 aberta.",
    "Porta4": "Alerta: porta 4 aberta.",
    "Porta6": "Alerta: porta 5 aberta.",
    "Porta7": "Alerta: porta 6 aberta.",
    "Porta8": "Alerta: porta 7 aberta.",
    "Porta9": "Alerta: porta 8 aberta.",
    "Porta10": "Alerta: porta 9 aberta.",
    "Porta1": "Alerta: porta esquerda lateral de acesso ao posicionador aberta.",
    "Porta11": "Alerta: porta de acesso ao rolinho e batedor aberta.",
    "Porta12": "Alerta: porta 12 aberta.",
    "Forno_Pino": "Alerta: pino do forno abaixado.",
    "Forno_CameSensor": "Alerta: came de entrada de pré-forma ligado mas sem identificação do sensor.",
    "Forno_PFTorna": "Alerta: sensor de pré-forma torta acionado.",
    "Forno_SegCamb": "Falha: segurança para evitar colisão entre cambotador e forno.",
    "FornoAquecendo": "Alerta: forno aquecendo, a temperatura do forno está abaixo do setpoint configurado.",
    "Mesa_Forn": "Alerta: segurança da mesa no forno, o cambotador deve estar na posição inicial.",
    "Mesa_Posi": "Alerta: segurança da mesa no posicionador, o cambotador deve estar na posição inicial.",
    "Camb_Inicio": "Alerta: segurança ao mover cambotador para posição inicial, a mesa deve estar parada.",
    "Camb_Forno": "Alerta: segurança do cambotador no forno, a mesa deve estar posicionada para o forno.",
    "Camb_Posi": "Alerta: segurança do cambotador no posicionador, a mesa deve estar para o posicionador e posicionador deve estar fechado.",
    "Posi_Camb": "Alerta: o cambotador deve estar na posição inicial para fechar o posicionador.",
    "Posi_Regu": "Alerta: recue a mesa do posicionador ou abra as pinças da régua 1.",
    "Posi_SensorRec": "Alerta: verifique os sensores do posicionador recuado.",
    "Posi_SensorAva": "Alerta: verifique os sensores do posicionador avançado.",
    "Regu_Camb": "Alerta: o cambotador deve estar na posição inicial para mover a régua para o posicionador.",
    "Regu_Posi": "Alerta: a prensa ou as pinças da régua devem estar abertas para mover a régua para o posicionador.",
    "Regu_MesaPosi": "Alerta: Para mover a régua para o posicionador, as pinças da régua devem estar abertas, a mesa do posicionador deve estar avançada, e o posicionador deve estar aberto.",
    "Regu_Pren": "Alerta: Para mover a régua para a prensa, as pinças da régua devem estar abertas e a mesa do posicionador recuada.",
    "Regu_Esti": "Alerta: Para mover a régua, o estiramento deve estar em cima ou as pinças da régua devem estar abertas.",
    "Regu_Bocal": "Alerta: Para mover a régua, as pinças devem estar abertas ou os bocais devem estar recuados.",
    "RampaEmergenciaRele": "Alerta: emergência da rampa acionada.",
    "RampaCarenagem": "Alerta: carenagem da rampa aberta.",
    "PFSilo": "Alerta: falta de pré-forma na rampa.",
    "PFRampaNivel": "Alerta: nivel de pré-forma na rampa baixo.",
    "FluxoH2O": "Alerta: fluxo de água desligado.",
    "LinhaStop": "Alerta: transporte aéreo cheio.",
    "SobretorqueRegu": "Alerta: sobretorque na régua na saída de garrafas.",
    "PressaoComandoDw": "Alerta: pressão de comando abaixo de 5bar.",
    "PressaoComandoUp": "Alerta: pressão de comando acima de 10 bar.",
    "PressaoSoproAlta": "Alerta: pressão de sopro acima do limite informado.",
    "PressaoSoproBaixa": "Alerta: pressão de sopro abaixo do limite informado.",
    "DescarregandoForno": "Alerta: forno descarregando.",
    "GraxaNivel": "Alerta: Nível de graxa baixo.",
    "Bocal1Pressao": "Alerta: garrafa estourada no bocal 1.",
    "Bocal2Pressao": "Alerta: garrafa estourada no bocal 2.",
    "Bocal3Pressao": "Alerta: garrafa estourada no bocal 3.",
    "Bocal4Pressao": "Alerta: garrafa estourada no bocal 4.",
    "Bocal5Pressao": "Alerta: garrafa estourada no bocal 5.",
    "Bocal6Pressao": "Alerta: garrafa estourada no bocal 6.",
    "Bocal7Pressao": "Alerta: garrafa estourada no bocal 7.",
    "Bocal8Pressao": "Alerta: garrafa estourada no bocal 8.",
    "CambFornSensor": "Alerta: erro na leitura do sensor do cambotador no forno.",
    "CambPosiSensor": "Alerta: erro na leitura do sensor do cambotador no posicionador.",
    "EstiSensorUp": "Alerta: erro na leitura do sensor de estiramento em cima.",
    "DI_RampaEmergencia1": "Alerta: botão de emergência do forno acionado, rampa parada.",
    "RampaEmergencia2": "Alerta: botão de emergência superior da rampa acionado, rampa parada.",
    "SW_Forn": "Alerta: STO do Forno desligado.",
    "SW_Mesa": "Alerta: STO da mesa desligado.",
    "SW_Camb": "Alerta: STO do Cambotador desligado.",
    "SW_Posi": "Alerta: STO do posicionador desligado.",
    "SW_Regu": "Alerta: STO da Régua desligado.",
    "SW_Pren": "Alerta: STO da prensa desligado.",
    "SW_Esti": "Alerta: STO do Estiramento desligado.",
    "TempFusoUp": "Alerta: temperatura do sensor superior do fuso está acima de 65 graus.",
    "TempFusoDw": "Alerta: temperatura do sensor inferior do fuso está acima de 65 graus.",
    "PressaoH2O": "Alerta: a pressão de água do molde deve estar entre 1.5 bar e 8 bar.",
    "PF_Travada_Alim": "Alerta: pré-forma travada no Alimentador",
    "LinhaComporta": "Alerta: Comporta aberta pelo sensor de linha parada da comporta",
    "SiloVazio": "Alerta: Silo está Vazio",
    "CorrentePrensaCl": "Alerta: corrente muito alta de prensa fechada (conferir ajuste)",
    "CorrenteFoldPrensa": "Alerta: corrente de regeneração muito baixa, risco de perda de posição",
    "LampQuebradaPF12_1": "Alerta: lampada quebrada ou queimada na zona 1 do preforno A.",
    "LampQuebradaPF12_2": "Alerta: lampada quebrada ou queimada na zona 2 do preforno A.",
    "LampQuebradaPF12_3": "Alerta: lampada quebrada ou queimada na zona 3 do preforno A.",
    "LampQuebradaPF12_4": "Alerta: lampada quebrada ou queimada na zona 4 do preforno A.",
    "LampQuebradaPF12_5": "Alerta: lampada quebrada ou queimada na zona 5 do preforno A.",
    "LampQuebradaPF12_6": "Alerta: lampada quebrada ou queimada na zona 6 do preforno A.",
    "LampQuebradaPF12_7": "Alerta: lampada quebrada ou queimada na zona 7 do preforno A.",
    "LampQuebradaPF12_8": "Alerta: lampada quebrada ou queimada na zona 8 do preforno A.",
    "LampQuebradaPF12_9": "Alerta: lampada quebrada ou queimada na zona 9 do preforno A.",
    "LampQuebradaPF34_1": "Alerta: lampada quebrada ou queimada na zona 1 do preforno B.",
    "LampQuebradaPF34_2": "Alerta: lampada quebrada ou queimada na zona 2 do preforno B.",
    "LampQuebradaPF34_3": "Alerta: lampada quebrada ou queimada na zona 3 do preforno B.",
    "LampQuebradaPF34_4": "Alerta: lampada quebrada ou queimada na zona 4 do preforno B.",
    "LampQuebradaPF34_5": "Alerta: lampada quebrada ou queimada na zona 5 do preforno B.",
    "LampQuebradaPF34_6": "Alerta: lampada quebrada ou queimada na zona 6 do preforno B.",
    "LampQuebradaPF34_7": "Alerta: lampada quebrada ou queimada na zona 7 do preforno B.",
    "LampQuebradaPF34_8": "Alerta: lampada quebrada ou queimada na zona 8 do preforno B.",
    "LampQuebradaPF34_9": "Alerta: lampada quebrada ou queimada na zona 9 do preforno B.",
    "LampQuebradaPF57_1": "Alerta: lampada quebrada ou queimada na zona 1 do preforno C.",
    "LampQuebradaPF57_2": "Alerta: lampada quebrada ou queimada na zona 2 do preforno C.",
    "LampQuebradaPF57_3": "Alerta: lampada quebrada ou queimada na zona 3 do preforno C.",
    "LampQuebradaPF57_4": "Alerta: lampada quebrada ou queimada na zona 4 do preforno C.",
    "LampQuebradaPF57_5": "Alerta: lampada quebrada ou queimada na zona 5 do preforno C.",
    "LampQuebradaPF57_6": "Alerta: lampada quebrada ou queimada na zona 6 do preforno C.",
    "LampQuebradaPF57_7": "Alerta: lampada quebrada ou queimada na zona 7 do preforno C.",
    "LampQuebradaPF57_8": "Alerta: lampada quebrada ou queimada na zona 8 do preforno C.",
    "LampQuebradaPF57_9": "Alerta: lampada quebrada ou queimada na zona 9 do preforno C.",
    "LampQuebradaF_1": "Alerta: lampada quebrada ou queimada na zona 1 do Forno.",
    "LampQuebradaF_2": "Alerta: lampada quebrada ou queimada na zona 2 do Forno.",
    "LampQuebradaF_3": "Alerta: lampada quebrada ou queimada na zona 3 do Forno.",
    "LampQuebradaF_4": "Alerta: lampada quebrada ou queimada na zona 4 do Forno.",
    "LampQuebradaF_5": "Alerta: lampada quebrada ou queimada na zona 5 do Forno.",
    "LampQuebradaF_6": "Alerta: lampada quebrada ou queimada na zona 6 do Forno.",
    "LampQuebradaF_7": "Alerta: lampada quebrada ou queimada na zona 7 do Forno.",
    "LampQuebradaF_8": "Alerta: lampada quebrada ou queimada na zona 8 do Forno.",
    "LampQuebradaF_9": "Alerta: lampada quebrada ou queimada na zona 9 do Forno.",
    "RampaEmergencia3": "Alerta: botao de emergencia do posicionador acionado, rampa parada.",
    "SobretorquePrensaFecha": "Alerta: sobretorque na prensa fechando",
    "SobretorquePrensaAbre": "Alerta: sobretorque na prensa abrindo",
    "LinhaDescarrega": "Alerta: sensor de descarregamento da saida de garrafas acionado.",
    "SegRampa": "Alerta: Falha de segurança na rampa, botão de emergência ou carenagem aberta."
}

fault = {
    "F_Forno ": "Falha: erro no drive do forno.",
    "F_Mesa": "Falha: erro no drive da Mesa.",
    "F_Camb": "Falha: erro no drive do cambotador.",
    "F_PosicUp": "Falha: erro no drive do posicionador Superior.",
    "F_PosicDw": "Falha: erro no drive do posicionador Inferior.",
    "F_Regua": "Falha: erro no drive da régua.",
    "F_Prensa": "Falha: erro no drive da prensa.",
    "Prensa": "Falha: erro no drive da prensa.",
    "F_Estira": "Falha: erro no drive do estiramento.",
    "StatusWord__Estira": "Falha: erro no drive do estiramento.",
    "StatusWord__Prensa": "Falha: erro no drive da prensa.",
    "StatusWord__Regua": "Falha: erro no drive da régua.",
    "StatusWord__Posic": "Falha: erro no drive do posicionador.",
    "StatusWord__Camb": "Falha: erro no drive do cambotador.",
    "StatusWord__Mesa": "Falha: erro no drive da Mesa.",
    "StatusWord__Forno": "Falha: erro no drive do forno.",
    "F_ControlStop": "Falha: Execução de Parada Controlada.",
    "F_CS_Forno": "Falha: parada Controlada do Forno (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Mesa": "Falha: parada Controlada da Mesa(Verifique o Sinal X7 - Pino 4)",
    "F_CS_Camb": "Falha: parada Controlada do Cambotador (Verifique o Sinal X7 - Pino 4)",
    "F_CS_PosicUp": "Falha: parada Controlada do Posicionador superior (Verifique o Sinal X7 - Pino 4)",
    "F_CS_PosicDw": "Falha: parada Controlada do Posicionador Inferior (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Regua": "Falha: parada Controlada da Régua (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Prensa": "Falha: parada Controlada da prensa (Verifique o Sinal X7 - Pino 4)",
    "F_CS_Estira": "Falha: parada Controlada do Estiramento (Verifique o Sinal X7 - Pino 4)",
    "F_OPStop": "Falha: erro detectado em algum drive, verifique as demais falhas.",
    "F_Emerg": "Alerta: emergência da rampa detectada",
    "F_ReleFase": "Falha: parada por relé de fase, verifique a tensão do equipamento.",
    "F_PortaAberta": "Falha: parada por portas abertas.",
    "F_PincaRegua1Fechada": "Falha: o sensor de régua 1 deve estar desligado quando o cilindro está avançado.",
    "F_PincaRegua1Aberta": "Falha: o sensor de régua 1 deve estar ligado quando o cilindro está recuado.",
    "F_PincaRegua2Fechada": "Falha: o sensor de régua 2 deve estar desligado quando o cilindro está avançado.",
    "F_PincaRegua2Aberta": "Falha: o sensor de régua 2 deve estar ligado quando o cilindro está recuado.",
    "F_Bocal1UP": "Falha: o sensor do bocal 1 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal1DW": "Falha: o sensor do bocal 1 deve estar ligado quando o cilindro está avançado.",
    "F_Bocal2UP": "Falha: o sensor do bocal 2 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal2DW": "Falha: o sensor do bocal 2 deve estar ligado quando o cilindro está avançado.",
    "F_Bocal3UP": "Falha: o sensor do bocal 3 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal3DW": "Falha: o sensor do bocal 3 deve estar ligado quando o cilindro está avançado.",
    "F_Bocal4UP": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F_Bocal4DW": "Falha: o sensor do bocal 4 deve estar desligado quando o cilindro está recuado.",
    "F_AvancMesaPosic": "Falha: os sensores da mesa do posicionador avançado devem estar ligados quando o cilindro está avançado.",
    "F_RecuaMesaPosic": "Falha: falha nos sensores de mesa recuada.",
    "F_SensorEstira": "Falha: o sensor do estiramento deve estar ligado quando o mesmo estiver em cima.",
    "F_PFTorta": "Falha: sensor de passagem de pré-forma acionado.",
    "F_PressaoCmdBaixa": "Falha: a pressão de comando ficou abaixo de 5bar.",
    "F_PressaoCmdAlta": "Falha: a pressão de comando ficou acima de 7bar.",
    "F_PinFornoAbaixado": "Falha: sensor do pino do forno embaixo acionado. Verifique o sensor próximo a alimentação de preformas.",
    "PinFornoAbaixado": "Falha: sensor do pino do forno embaixo acionado. Verifique o sensor próximo a alimentação de preformas.",
    "F_CambotadorColisao": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "F_PosicReguaColisao": "Falha: colisão da posicionador e régua.",
    "F_TorqueForno": "Falha: sobretorque no forno.",
    "F_PosicReguaColisao": "Falha: colisão da posicionador e régua.",
    "F_QuedaPF_no_preForno": "Falha: rotina de queda de preforma no pré-forno ativada, verifique o forno.",
    "F_Camb_no_Forno": "Falha: colisão entre cambotador e forno, verifique o conjunto.",
    "boZeraFalha": "Reset de falhas.",
    "StatusWord__PosicUp": "Falha: erro no drive do posicionador Superior.",
    "StatusWord__PosicDw": "Falha: erro no drive do posicionador Inferior.",
    "Forn": "Falha: drive do forno.",
    "Mesa": "Falha: drive da mesa.",
    "Camb": "Falha: drive do Camb.",
    "Posi": "Falha: drive do Posicionador.",
    "Regu": "Falha: drive da Régua.",
    "Pren": "Falha: drive da prensa.",
    "Esti": "Falha: drive do estiramento.",
    "Emergencia1": "Falha: emergência do painel de operação acionada.",
    "ReleFFase": "Falha: rele falta de fase acionado.",
    "Portas": "Falha: portas abertas com equipamento operando.",
    "Porta1": "Falha: porta direita de acesso lateral ao forno aberta.",
    "Porta2": "Falha: porta 2 aberta.",
    "Porta3": "Falha: porta 3 aberta.",
    "Porta4": "Falha: porta 4 aberta.",
    "Porta5": "Falha: porta 5 aberta.",
    "Porta6": "Falha: porta 6 aberta.",
    "Porta7": "Falha: porta 7 aberta.",
    "Porta8": "Falha: porta 8 aberta.",
    "Porta9": "Falha: porta 9 aberta.",
    "Porta10": "Falha: porta esquerda lateral de acesso ao posicionador aberta.",
    "Porta11": "Falha: porta de acesso ao rolinho e batedor aberta.",
    "Porta12": "Falha: porta 12 aberta.",
    "Forno_Pino": "Falha: sensor pino do forno abaixado detectado.",
    "Forno_CameSensor": "Falha: sensor do came detectado.",
    "Forno_PFTorna": "Falha: sensor de pré-forma torta detectado.",
    "Forno_SegCamb": "Falha: segurança do cambotador acionada para evitar colisão com forno.",
    "FornoTorque": "Falha: sobretorque no forno identificado.",
    "FornoQuedaPF": "Falha: Queda de preforma detectada no preforno.",
    "Camb_Forno": "Falha: segurança para evitar colisão entre cambotador e forno.",
    "Camb_Posi": "Falha: segurança para evitar colisão entre cambotador e posicionador.",
    "Camb_Regu": "Falha: segurança para evitar colisão entre cambotador e régua.",
    "Camb_Sensor1": "Falha: erro na leitura do sensor do cambotador no forno.",
    "Camb_Sensor2": "Falha: erro na leitura do sensor do cambotador no posicionador.",
    "Posi_Camb": "Falha: segurança para evitar colisão entre posicionador e cambotador.",
    "Posi_Regu": "Falha: segurança para evitar colisão entre mesa do posicionador recuada e régua.",
    "Posi_SensorRec": "Falha: erro na leitura dos sensores da mesa do posicionador recuada.",
    "Posi_SensorAva": "Falha: erro na leitura dos sensores da mesa do posicionador avançada.",
    "Regu_MesaPosi": "Falha: segurança para evitar colisão entre posicionador e pinça da régua 1 fechada.",
    "Regu_Camb": "Falha: segurança para evitar colisão entre régua e cambotador.",
    "Regu_Pren": "Falha: segurança para evitar colisão entre régua com pinças fechadas com a prensa fechada.",
    "Regu_Esti": "Falha: segurança para evitar colisão entre régua com pinças fechadas com as varetas do estiramento.",
    "Regu_Bocal": "Falha: segurança para evitar colisão entre régua com pinças fechadas com bocais embaixo.",
    "EstiSensor": "Falha: erro na leitura do sensor do estiramento em cima.",
    "Bocal1Dw": "Falha: erro na leitura do sensor do bocal 1 embaixo.",
    "Bocal2Dw": "Falha: erro na leitura do sensor do bocal 2 embaixo.",
    "Bocal1Up": "Falha: sensor do bocal 1 acionado com bocal desligado.",
    "Bocal2Up": "Falha: sensor do bocal 2 acionado com bocal desligado.",
    "PressaoComandoDw": "Falha: detectado pressão de comando abaixo de 5bar necessários para funcionamento.",
    "PressaoComandoUp": "Falha: detectado pressão de comando acima de 10bar permitidos para funcionamento.",
    "GraxaCiclo": "Falha: problema na bomba de graxa, erro na contagem interna de ciclos.",
    "EmergenciaRele": "Falha: emergência acionada.",
    "Ethercat": "Falha: Erro na comunicação Ethercat.",
    "TempFusoUp": "Falha: temperatura do sensor superior  do fuso acima do limite de 70 graus.",
    "TempFusoDw": "Falha: temperatura do sensor inferior  do fuso acima do limite de 70 graus.",
    "Emergencia2": "Falha: emergência da carenagem pressionada.",
    "Forno_PFnoCorrentao": "Falha: Sensor de Pre Forma caida no correntão do forno acionado",
    "CPX_Festo": "Falha: modulos de I/O da Festo",
    "PrensaFechando": "Falha:prensa fechando, verifique a existência de algum objeto caido na prensa",
    "FornoQuedaForno": "Falha: Queda de preforma detectada no forno.",
}
